---
title: "Analisis_estadístico_experimentos_A_gangetica"
author: "Antonio"
date: '2022-06-25'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Primer experimento ruptura de dormancia en semillas de Asystasia gangetica 

```{r datos de dormancia}
library(pacman)
p_load(readxl, tidyverse,agricolae)
#file.choose()
ruta_1 <- "C:\\Users\\Jose R\\Desktop\\OneDrive_2022-06-25\\1. Curso_Investigación\\R_analysis\\dormancia.xlsx"
data_dor <- lapply(excel_sheets(ruta_1), read_excel, path = ruta_1)
data_dor <- data_dor[[1]]
data_dor$Acumulado <- as.numeric(data_dor$Acumulado)

#La variable respuesta es el acumulado porcentual
  data_dor <-
    data_dor %>%
    mutate(Tratamiento = factor(Tratamiento), 
           DDS = as.numeric(DDS),
           Acumulado = ((Acumulado/50)*100))
 
  
data_dor %>%
  ggplot(aes(x=DDS, y=Acumulado)) +
  geom_point() + geom_line() +
  facet_grid(~Tratamiento,
             labeller = labeller(
               Tratamiento = c("T1" = "KNO3 (5 %) durante 12 horas",
                          "T2" = "40 °C durante 1 hora",
                          "T3" = "40 °C durante 2 hora",
                          "T4" = "4 °C durante 4 horas + 30 °C durante 4 horas",
                          "T5" = "4 °C durante 8 horas + 30 °C durante 16 horas", 
                          "T6" = "40 °C y 60 °C durante 1 minuto"))) +
               labs(x="DDS", y="Acumulado de semillas germinadas (%)") 
 



```


```{r Area bajo la curva}
library(agricolae)

abcg_data <-
    data_dor %>%
      group_by(Tratamiento) %>%
        summarise(ABCG = audpc(Acumulado,DDS)%>% round(0))

abcg_data
```

```{r Representación gráfica2}
library(pacman)
p_load(readxl, tidyverse,agricolae)
#file.choose()
ruta_1 <- "C:\\Users\\Jose R\\Desktop\\OneDrive_2022-06-25\\1. Curso_Investigación\\R_analysis\\dormancia.xlsx"
data_dor <- lapply(excel_sheets(ruta_1), read_excel, path = ruta_1)
data_dor <- data_dor[[2]]
data_dor$Semillas.germinadas <- as.numeric(data_dor$Semillas.germinadas)

 data_dor <-
    data_dor %>%
   group_by(DDS, Tratamiento) %>% 
    mutate(Tratamiento = factor(Tratamiento), 
           DDS = as.numeric(DDS),
           Promedio = mean(Semillas.germinadas))


plot <- data_dor %>% 
 ggplot(aes(x= DDS, y= Promedio )) + 
  geom_point() +
  geom_line() +
     scale_x_continuous(limits = c(0, 10))+
      scale_y_continuous(limits = c(0, 20))+
         facet_wrap(~Tratamiento,
             labeller = labeller(
               Tratamiento = c("T1" = "KNO3 (5 %) durante 12 horas",
                          "T2" = "40 °C durante 1 hora",
                          "T3" = "40 °C durante 2 hora",
                          "T4" = "4 °C durante 4 horas + 30 °C durante 4 horas",
                          "T5" = "4 °C durante 8 horas + 30 °C durante 16 horas", 
                          "T6" = "40 °C y 60 °C durante 1 minuto")))+
                          theme_classic()
  
    f_labels <- data.frame(Tratamiento = c("T1", "T2", "T3", "T4", "T5", "T6"), label = c("ABCG = 215 n°semillas*dias",
                                       "ABCG = 495  n°semillas*dias",
                                       "ABCG = 407  n°semillas*dias",
                                       "ABCG = 373  n°semillas*dias",
                                       "ABCG = 483  n°semillas*dias", 
                                       "ABCG = 546  n°semillas*dias"))
  
  ABCG_plot<- plot + geom_text(x = 6, y = 90, aes(label = label), data= f_labels)
  

a <-left_join(data_dor, abcg_data, by = "Tratamiento") %>% 
  mutate(ABCG = factor(ABCG),
         Tratamiento = paste(Tratamiento, "(AUDPC =", abcg_data,"n°semillas*dias"))
  

data_dor %>% 
  ggplot(aes(x=DDS, y=Acumulado, group=Tratamiento, shape=Tratamiento)) + 
  geom_point(aes(y=Acumulado),size=2.5) +
  geom_line() +
  labs(x="DDS", y="Acumulado de semillas germinadas (%)") +
  scale_y_continuous(limits = c(0,100)) +
  theme_classic() +
  theme(legend.position = c(0.35, 0.9),legend.title = element_blank())

  


```

```{r Representación gráfica_FINAL}
windowsFonts(A = windowsFont("Arial"))

plot <- data_dor %>% 
 ggplot(aes(x= DDS, y= Acumulado)) + 
  geom_point(size = 3) +
  geom_line() +
     scale_x_continuous(limits = c(0, 10), breaks = seq(0,10,1))+
      scale_y_continuous(limits = c(0, 100))+
      labs(x = "Tiempo (DDS)" , y = "Germinación acumulada (%)" )+
         facet_wrap(~Tratamiento,
             labeller = labeller(
               Tratamiento = c("T1" = "KNO3 (5 %) durante 12 horas",
                          "T2" = "40 °C durante 1 hora",
                          "T3" = "40 °C durante 2 hora",
                          "T4" = "4 °C durante 4 horas + 30 °C durante 4 horas",
                          "T5" = "4 °C durante 8 horas + 30 °C durante 16 horas", 
                          "T6" = "40 °C y 60 °C durante 1 minuto")))+
                          theme_classic() +
              theme(axis.text.x = element_text(colour = "black", family = "A"),
                  axis.text.y = element_text(colour = "black", family = "A"),
                  #axis.text.x = element_text(colour = "black", family = "A", size = 14),
                  axis.line = element_line(color = "black"),
                  legend.position = "none", 
                  plot.title = element_text(hjust = 0.5, size = 14.5),
                  axis.title.y = element_text(size = 17),
                  axis.title.x = element_text(size = 17), 
                  strip.text.x  = element_text(size = 17, family = "A"),
                  #strip.background = element_blank(),
                  panel.grid.minor = element_blank(),
                  panel.grid.major = element_blank(),
                  text = element_text(size = 23, family = "A", colour = "black"))

    f_labels <- data.frame(Tratamiento = c("T1", "T2", "T3", "T4", "T5", "T6"), 
                          label = c("ABCG = 215 n°semillas*dias",
                                       "ABCG = 495  n°semillas*dias",
                                       "ABCG = 407  n°semillas*dias",
                                       "ABCG = 373  n°semillas*dias",
                                       "ABCG = 483  n°semillas*dias", 
                                       "ABCG = 546  n°semillas*dias"))
  
  ABCG_plot<- plot + geom_text(x = 6, y = 90, aes(label = label), data= f_labels, size = 6)
  ggsave("plot_0.png", plot = ABCG_plot, width = 40, height = 29, units = c("cm"), dpi = 500)
########################################################################################
a <-left_join(data_dor, abcg_data, by = "Tratamiento") %>% 
  mutate(ABCG = factor(ABCG),
         Tratamiento = paste(Tratamiento, "(AUDPC =", abcg_data,"n°semillas*dias"))
  

data_dor %>% 
  ggplot(aes(x=DDS, y=Acumulado, group=Tratamiento, shape=Tratamiento)) + 
  geom_point(aes(y=Acumulado),size=2.5) +
  geom_line() +
  labs(x="DDS", y="Acumulado de semillas germinadas (%)") +
  scale_y_continuous(limits = c(0,100)) +
  theme_classic() +
  theme(legend.position = c(0.35, 0.9),legend.title = element_blank())
###################################################################################
  


```


```{r ANOVA 6 TRATAMIENTOS}
library(pacman)
p_load(readxl, tidyverse,agricolae)
#file.choose()
ruta_1 <- "C:\\Users\\Jose R\\Desktop\\OneDrive_2022-06-25\\1. Curso_Investigación\\R_analysis\\dormancia.xlsx"
data_dor <- lapply(excel_sheets(ruta_1), read_excel, path = ruta_1)
data_dor <- data_dor[[2]]
data_dor$Semillas.germinadas <- as.numeric(data_dor$Semillas.germinadas)

#Agrupamiento por réplica
#data_dor <- data_dor %>% 
 # group_by(Tratamiento,Replica, DDS) %>% 
  #summarise(sumatoria = round(sum(Semillas.germinadas)/17)*100)

#aplicar area bajo la curva

data_dor <-
    data_dor %>%
    mutate(Tratamiento = factor(Tratamiento), 
           Replica = factor(Replica))



abcg_data <-
    data_dor %>%
      group_by(Tratamiento, Replica) %>%
        summarise(ABCG = audpc(Semillas.germinadas,DDS)%>% round(0))

abcg_data
#Realizar el modelo lineal para ver si hay diferencias entre tratamientos
lin_mod<-lm(ABCG~Tratamiento + Replica, data = abcg_data)
summary(lin_mod)

model<-aov(lin_mod)
print(LSD.test(model,"Tratamiento"))

summary(lin_mod)
#Modelo lineal para ver si hay diferencias en el tiempo
#Agrupamiento por réplica

#data_dor_di <- data_dor 
  #group_by(Tratamiento, DDS) %>% 
  #summarise(sumatoria = round((sum(Semillas.germinadas/50)*100)))


multifit <- 
  fit_multi(time_col = "DDS",
            intensity_col = "Acumulado",
            data = data_dor,
            strata_col = c("Tratamiento"),
            starting_par = list(y0 = 0.01, r = 0.03),
            maxiter = 1024,
            nlin = TRUE, 
            estimate_K = FALSE)




lin_audpc <- lm(Semillas.germinadas~Tratamiento + DDS, data = data_dor_di)






#La variable respuesta es el acumulado porcentual
  data_dor <-
    data_dor %>%
    mutate(Tratamiento = factor(Tratamiento), 
           DDS = as.numeric(DDS),
           Acumulado = ((Acumulado/50)*100)) 



lin_audpc <- lm(ABCG ~ Tratamiento +, data = abcg_data)
summary(lin_audpc)
anova_test<-aov(lin_audpc)

summary(anova_test)


```







```{r NO}
  data_dor <-
    data_dor %>%
    mutate(Tratamiento = factor(Tratamiento), 
           DDS = as.numeric(DDS),
           Acumulado = ((Acumulado/50)*100)) 

data_dor %>% 
  ggplot(aes(x= DDS, y= Acumulado)) + 
  geom_point() +
  geom_line() +
  facet_wrap(.~Tratamiento) + 
  labs(x="DDS", y="Acumulado de semillas germinadas (%)")+
                    geom_text(data =ann_text,label = c("ABCG = 215 n°semillas*dias",
                                       "ABCG = 495  n°semillas*dias",
                                       "ABCG = 407  n°semillas*dias",
                                       "ABCG = 373  n°semillas*dias",
                                       "ABCG = 483  n°semillas*dias", 
                                       "ABCG = 546  n°semillas*dias"))

ann_text <- data.frame(DDS = 10,
                       Acumulado= 10,
  Tratamiento = c("KNO3 (5 %) durante 12 horas",  "40 °C durante 1 hora", "40 °C durante 2 hora",
   "4 °C durante 4 horas + 30 °C durante 4 horas", "4 °C durante 8 horas + 30 °C durante 16 horas", "40 °C y 60 °C durante 1 minuto"))

ann_text

```

```{r NO}

  data_plot <- 
  data_dor %>% 
  group_by(DDS, Tratamiento) 

data_plot %>% 
 ggplot(aes(x= DDS, y= Acumulado)) + 
  geom_point() +
  geom_line() +
  facet_wrap(.~Tratamiento)+
  geom_text(data = ann_text, label = c("ABCG = 215 n°semillas*dias",
                                       "ABCG = 495  n°semillas*dias",
                                       "ABCG = 407  n°semillas*dias",
                                       "ABCG = 373  n°semillas*dias",
                                       "ABCG = 483  n°semillas*dias", 
                                       "ABCG = 546  n°semillas*dias"), size = 3.2)
 ann_text <- data.frame(DDS = 6, #posiciones de las etiquetas
                        Acumulado=100,
   Tratamiento =c("KNO3 (5 %) durante 12 horas",
                            "40 °C durante 1 hora", 
                            "40 °C durante 2 horas", 
                            "4 °C durante 4 horas + 30 °C durante 4 horas", 
                            "4 °C durante 8 horas + 30 °C durante 16 horas", 
                            "40 °C y 60 °C durante 1 minuto"))

#############################################################################









  geom_text(data =data_dor$Tratamiento,label = c("ABCG = 215 n°semillas*dias",
                                       "ABCG = 495  n°semillas*dias",
                                       "ABCG = 407  n°semillas*dias",
                                       "ABCG = 373  n°semillas*dias",
                                       "ABCG = 483  n°semillas*dias", 
                                       "ABCG = 546  n°semillas*dias"))

  
  


```

```{r NO}
plot <- data_dor %>% 
 ggplot(aes(x= DDS, y= Acumulado)) + 
  geom_point() +
  geom_line() +
     scale_x_continuous(limits = c(0, 10))+
      scale_y_continuous(limits = c(0, 100))+
         facet_wrap(~Tratamiento,
             labeller = labeller(
               Tratamiento = c("T1" = "KNO3 (5 %) durante 12 horas",
                          "T2" = "40 °C durante 1 hora",
                          "T3" = "40 °C durante 2 hora",
                          "T4" = "4 °C durante 4 horas + 30 °C durante 4 horas",
                          "T5" = "4 °C durante 8 horas + 30 °C durante 16 horas", 
                          "T6" = "40 °C y 60 °C durante 1 minuto")))+
                          theme_classic()
  
    f_labels <- data.frame(Tratamiento = c("T1", "T2", "T3", "T4", "T5", "T6"), label = c("ABCG = 215 n°semillas*dias",
                                       "ABCG = 495  n°semillas*dias",
                                       "ABCG = 407  n°semillas*dias",
                                       "ABCG = 373  n°semillas*dias",
                                       "ABCG = 483  n°semillas*dias", 
                                       "ABCG = 546  n°semillas*dias"))
  
  ABCG_plot<- plot + geom_text(x = 6, y = 90, aes(label = label), data= f_labels)
  

a <-left_join(data_dor, abcg_data, by = "Tratamiento") %>% 
  mutate(ABCG = factor(ABCG),
         Tratamiento = paste(Tratamiento, "(AUDPC =", abcg_data,"n°semillas*dias"))
  

data_dor %>% 
  ggplot(aes(x=DDS, y=Acumulado, group=Tratamiento, shape=Tratamiento)) + 
  geom_point(aes(y=Acumulado),size=2.5) +
  geom_line() +
  labs(x="DDS", y="Acumulado de semillas germinadas (%)") +
  scale_y_continuous(limits = c(0,100)) +
  theme_classic() +
  theme(legend.position = c(0.35, 0.9),legend.title = element_blank())

lin_audpc <- lm(ABCG ~ Tratamiento, data = abcg_data)
summary(lin_audpc)
anova(lin_audpc)
  

  
 
```

